### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by MichaelTiebesl** [hayderctee/masalla-icon-theme#3]
I updated a few icons what looks better to me. Also the color of the folder i changed. I like the icons more universal. So much square all icons as possible. Also i think png are not necessary. Correct me if I'm wrong. If i have time next week i will fork it here. Are you also working on it to make it on AUR and a PPA? I can do that but i don't have so much time to maintain that. 

![schermafdruk van 2015-10-21 13-43-14](https://cloud.githubusercontent.com/assets/10792019/10628624/f072978e-77f9-11e5-8d05-1375dc02f3e5.png)

![menu](https://cloud.githubusercontent.com/assets/10792019/10628716/ad7727d2-77fa-11e5-8bef-7eac22bae029.png)

**Comment by hayderctee** [comment]
It's just amazing work !!!!!!!! i think you should wait the next version of masalla because it's have more compatibility with kde and more icons :) 
the icons is still in beta version so i'm working to make all icons in square shape , but now i'm working on mimetype and other color set , and yes please if you can to put it in AUR and PPA

**Comment by hayderctee** [comment]
I have applied many of your feedback
Thanks for all opinion that have helped to make this work better
